version: "3"
services:
  bharat-mongo:
    image: mongo:latest
    container_name: "bharat-mongo"
    ports:
      - 27017:27017
  bharat:
    image: mongodbexample-0.0.1
    container_name: bharat

    ports:
      - 8080:8080
    links:
      - bharat-mongo



